#!/bin/sh

DISABLE_INITIAL_NOTIFICATIONS=1
DISABLE_DISK_CACHE=1
DISABLE_HISTORY=1
DISABLE_DOM_STORAGE=0
DISABLE_INDEXEDDB=0
DISABLE_MISC_REMOTE=1

DISABLE_JAVASCRIPT=0
DISABLE_JAVASCRIPT_ASM=1
DISABLE_JAVASCRIPT_JIT=1

DISABLE_CLIPBOARD_AUTOCOPY=1
DISABLE_CONTEXT_MENU=1
DISABLE_EME=1
DISABLE_GECKO_MEDIA_PLUGINS=1
DISABLE_GEOLOCATION=1
DISABLE_HARDWARE_ACCELERATION=1
DISABLE_SOCIAL=1
DISABLE_UNSAFE_FONT_RENDERING=1
DISABLE_WEBIDE=1
DISABLE_WEBGL=1
DISABLE_WEBRTC=1
DISABLE_WEB_NOTIFICATIONS=0

DISABLE_PLUGINS=1
DISABLE_HELLO=1
DISABLE_PDFJS=1
DISABLE_POCKET=1
DISABLE_READER=1

NETWORK_HARDEN=1
NETWORK_REFERER_HEADER=1

TLS_DISABLE_ARCFOUR_CIPHERS=1
TLS_DISABLE_TRIPLEDES_CIPHERS=1
TLS_DISABLE_DHE_CIPHERS=1
TLS_DISABLE_NONPFS_CIPHERS=0
TLS_HARDEN=1
TLS_OCSP_REQUIRE=0
TLS_VERSION_MIN=1

FINGERPRINT_PROTECTION=1
PRIVATE_BROWSING_AUTOSTART=1
TBB_USERAGENT=0
TRACKING_PROTECTION=1

if [ $# -eq 1 ]; then
    if [ "$1" = '-h' ] || [ "$1" = '--help' ] || [ "$1" = 'help' ]; then
        cat << EOF
Usage: securemyfirefox
 or:   securemyfirefox CONFIG_FILE

securemyfirefox enhances the security and privacy of Firefox. It generates user
preferences to standard output. Save the output as 'user.js' in your Firefox
profile (ie, ~/.firefox/xxxxxxxx.default/user.js) and restart Firefox.
EOF
    exit 0
    fi

    conf="`readlink -f "$1"`"
    if [ ! -e "$conf" ]; then
        printf '%s\n' "securemyfirefox: cannot access '$conf': No such file"
        printf '%s\n' "Try 'securemyfirefox -h' for more information."
        exit 1
    else
        . "$conf"
    fi
fi

cat << EOF
/* First line must be a comment */

EOF

if [ "$DISABLE_INITIAL_NOTIFICATIONS" = 1 ]; then
    cat << EOF
// Disable initial notifications
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.notificationDisabled", true);
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":0, \"passwords\":0, \"bookmarks\":0}");
user_pref("browser.uitour.enabled", false);
user_pref("devtools.devedition.promo.shown", true);
user_pref("general.warnOnAboutConfig", false);
user_pref("pdfjs.firstrun", false);
user_pref("reader.detectedFirstArticle", true);
user_pref("startup.homepage_override_url", "");
user_pref("startup.homepage_welcome_url", "");
user_pref("startup.homepage_welcome_url.additional", "");

EOF
fi

if [ "$DISABLE_DISK_CACHE" = 1 ]; then
    cat << EOF
// Disable disk cache
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.offline.enable", false);

EOF
fi

if [ "$DISABLE_HISTORY" = 1 ]; then
    cat << EOF
// Disable history
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.helperApps.deleteTempFileOnExit", true);
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.slowStartup.maxSamples", 0);
user_pref("browser.slowStartup.notificationDisabled", true);
user_pref("layout.css.visited_links_enabled", false);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("places.history.enabled", false);
user_pref("privacy.clearOnShutdown.cache", true);
user_pref("privacy.clearOnShutdown.cookies", true);
user_pref("privacy.clearOnShutdown.downloads", true);
user_pref("privacy.clearOnShutdown.formdata", true);
user_pref("privacy.clearOnShutdown.history", true);
user_pref("privacy.clearOnShutdown.offlineApps", true);
user_pref("privacy.clearOnShutdown.passwords", true);
user_pref("privacy.clearOnShutdown.sessions", true);
user_pref("privacy.clearOnShutdown.siteSettings", true);
user_pref("privacy.clearOnShutdown.openWindows", true);
user_pref("security.nocertdb", true);
user_pref("signon.autofillForms", false);
user_pref("signon.rememberSignons", false);

EOF
fi

if [ "$DISABLE_DOM_STORAGE" = 1 ]; then
    cat << EOF
// Disable DOM storage
user_pref("dom.storage.enabled", false);

EOF
fi

if [ "$DISABLE_GEOLOCATION" = 1 ]; then
    cat << EOF
// Disable geolocation
user_pref("browser.search.geoSpecificDefaults", false);
user_pref("browser.search.geoip.url", "");
user_pref("geo.enabled", false);
user_pref("geo.wifi.uri", "");

EOF
fi

if [ "$DISABLE_INDEXEDDB" = 1 ]; then
    cat << EOF
// Disable IndexedDB
user_pref("dom.indexedDB.enabled", false);

EOF
fi

if [ "$DISABLE_MISC_REMOTE" = 1 ]; then
    cat << EOF
// Disable miscellaneous remote connections
user_pref("beacon.enabled", false);
user_pref("browser.aboutHomeSnippets.updateUrl", "");
user_pref("browser.casting.enabled", false);
user_pref("browser.newtab.preload", false);
user_pref("browser.newtabpage.directory.ping", "");
user_pref("browser.newtabpage.directory.source", "");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.pinned", "");
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.selfsupport.url", "");
user_pref("browser.send_pings", false);
user_pref("browser.snippets.enabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("experiments.enabled", false);
user_pref("experiments.supported", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("network.allow-experiments", false);
user_pref("toolkit.telemetry.enabled", false);

EOF
fi

if [ "$DISABLE_JAVASCRIPT" = 1 ]; then
    DISABLE_JAVASCRIPT_ASM=1
    DISABLE_JAVASCRIPT_JIT=1
    cat << EOF
// Disable JavaScript
user_pref("javascript.enabled", false);

EOF
fi

if [ "$DISABLE_JAVASCRIPT_ASM" = 1 ]; then
    cat << EOF
// Disable JavaScript ASM.js
user_pref("javascript.options.asmjs", false);

EOF
fi

if [ "$DISABLE_JAVASCRIPT_JIT" = 1 ]; then
    cat << EOF
// Disable JavaScript Just-In-Time compiler
user_pref("javascript.options.baselinejit", false);
user_pref("javascript.options.ion", false);

EOF
fi

if [ "$DISABLE_CLIPBOARD_AUTOCOPY" = 1 ]; then
    cat << EOF
// Disable clipboard autocopy
user_pref("clipboard.autocopy", false);
user_pref("dom.event.clipboardevents.enabled", false);

EOF
fi

if [ "$DISABLE_CONTEXT_MENU" = 1 ]; then
    cat << EOF
// Forbid websites from modifying right-click menu
user_pref("dom.event.contextmenu.enabled", false);

EOF
fi

if [ "$DISABLE_EME" = 1 ]; then
    cat << EOF
// Disable Encrypted Media Extensions
user_pref("browser.eme.ui.enabled", false);
user_pref("media.eme.apiVisible", false);
user_pref("media.eme.enabled", false);
user_pref("media.gmp-eme-adobe.enabled", false);

EOF
fi

if [ "$DISABLE_GECKO_MEDIA_PLUGINS" = 1 ]; then
    cat << EOF
// Disable Cisco codec
user_pref("media.gmp-gmpopenh264.enabled", false);
user_pref("media.gmp-manager.url", "");
user_pref("media.gmp-provider.enabled", false);

EOF
fi

if [ "$DISABLE_HARDWARE_ACCELERATION" = 1 ]; then
    cat << EOF
// Disable hardware acceleration
user_pref("layers.acceleration.disabled", true);

EOF
fi

if [ "$DISABLE_SOCIAL" = 1 ]; then
    cat << EOF
// Disable social integration
user_pref("social.directories", "");
user_pref("social.remote-install.enabled", false);
user_pref("social.share.activationPanelEnabled", false);
user_pref("social.shareDirectory", "");
user_pref("social.toast-notifications.enabled", false);
user_pref("social.whitelist", "");

EOF
fi

if [ "$DISABLE_UNSAFE_FONT_RENDERING" = 1 ]; then
    cat << EOF
// Disable unsafe font rendering
user_pref("gfx.font_rendering.graphite.enabled", false);
user_pref("gfx.font_rendering.opentype_svg.enabled", false);

EOF
fi

if [ "$DISABLE_WEBIDE" = 1 ]; then
    cat << EOF
// Disable WebIDE
user_pref("devtools.appmanager.enabled", false);
user_pref("devtools.webide.autoinstallADBHelper", false);
user_pref("devtools.webide.autoinstallFxdtAdapters", false);
user_pref("devtools.webide.enabled", false);

EOF
fi

if [ "$DISABLE_WEBGL" = 1 ]; then
    cat << EOF
// Disable WebGL
user_pref("webgl.disable-extensions", true);
user_pref("webgl.disabled", true);
user_pref("webgl.min_capability_mode", true);

EOF
fi

if [ "$DISABLE_WEBRTC" = 1 ]; then
    DISABLE_HELLO=1
    cat << EOF
// Disable WebRTC
user_pref("media.getusermedia.screensharing.allowed_domains", "");
user_pref("media.getusermedia.screensharing.enabled", false);
user_pref("media.navigator.enabled", false);
user_pref("media.navigator.video.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.video.enabled", false);

EOF
fi

if [ "$DISABLE_WEB_NOTIFICATIONS" = 1 ]; then
    cat << EOF
// Disable web notifications
user_pref("dom.webnotifications.enabled", false);

EOF
fi

if [ "$DISABLE_PLUGINS" = 1 ]; then
    cat << EOF
// Disable plugins
user_pref("plugin.default.state", 0);
user_pref("plugin.disable", true);
user_pref("plugin.state.flash", 0);
user_pref("plugin.state.java", 0);
user_pref("plugins.enumerable_names", "");
user_pref("security.xpconnect.plugin.unrestricted", false);

EOF
fi

if [ "$DISABLE_HELLO" = 1 ]; then
    cat << EOF
// Disable Firefox Hello
user_pref("loop.enabled", false);

EOF
fi

if [ "$DISABLE_PDFJS" = 1 ]; then
    cat << EOF
// Disable PDF.js
user_pref("pdfjs.disabled", true);

EOF
fi

if [ "$DISABLE_POCKET" = 1 ]; then
    cat << EOF
// Disable Pocket
user_pref("browser.pocket.enabled", false);

EOF
fi

if [ "$DISABLE_READER" = 1 ]; then
    cat << EOF
// Disable Reader View
user_pref("reader.parse-on-load.enabled", false);

EOF
fi

if [ "$NETWORK_HARDEN" = 1 ]; then
    cat << EOF
// Network hardening
user_pref("browser.fixup.alternate.enabled", false);
user_pref("network.IDN_show_punycode", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.dns.disablePrefetchFromHTTPS", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.proxy.socks_remote_dns", true);

EOF
fi

if [ "$NETWORK_REFERER_HEADER" -ge 0 ]; then
    cat << EOF
// Send referer header: 0=never 1=links 2=links+images
user_pref("network.http.sendRefererHeader", $NETWORK_REFERER_HEADER);

EOF
fi

if [ "$TLS_DISABLE_NONPFS_CIPHERS" = 1 ]; then
    TLS_DISABLE_ARCFOUR_CIPHERS=1
    TLS_DISABLE_TRIPLEDES_CIPHERS=1
    cat << EOF
// Disable TLS ciphers that do not utilize perfect forward secrecy
user_pref("security.ssl3.rsa_aes_128_sha", false);
user_pref("security.ssl3.rsa_aes_256_sha", false);

EOF
fi

if [ "$TLS_DISABLE_ARCFOUR_CIPHERS" = 1 ]; then
    cat << EOF
// Disable TLS RC4 ciphers
user_pref("security.tls.unrestricted_rc4_fallback", false);
user_pref("security.ssl3.rsa_rc4_128_sha", false);
user_pref("security.ssl3.rsa_rc4_128_md5", false);
user_pref("security.ssl3.ecdhe_rsa_rc4_128_sha", false);
user_pref("security.ssl3.ecdhe_ecdsa_rc4_128_sha", false);

EOF
fi

if [ "$TLS_DISABLE_TRIPLEDES_CIPHERS" = 1 ]; then
    cat << EOF
// Disable TLS 3DES ciphers
user_pref("security.ssl3.rsa_des_ede3_sha", false);

EOF
fi

if [ "$TLS_DISABLE_DHE_CIPHERS" = 1 ]; then
    cat << EOF
// Disable DHE ciphers to protect against weak DH groups
user_pref("security.ssl3.dhe_rsa_aes_128_sha", false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha", false);

EOF
fi

if [ "$TLS_HARDEN" = 1 ]; then
    cat << EOF
// TLS hardening
user_pref("security.cert_pinning.enforcement_level", 2);
user_pref("security.enable_tls_session_tickets", false);
user_pref("security.mixed_content.block_active_content", true);
user_pref("security.mixed_content.block_display_content", true);
user_pref("security.ssl.treat_unsafe_negotiation_as_broken", true);

EOF
fi

if [ "$TLS_OCSP_REQUIRE" = 1 ]; then
    cat << EOF
// Require OCSP
user_pref("security.OCSP.require", true);

EOF
fi

if [ "$TLS_VERSION_MIN" -gt 0 ]; then
    cat << EOF
// TLS minimum protocol version
user_pref("security.tls.version.min", $TLS_VERSION_MIN);

EOF
fi

if [ "$FINGERPRINT_PROTECTION" = 1 ]; then
    cat << EOF
// Protect against fingerprinting
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.zoom.siteSpecific", false);
user_pref("device.sensors.enabled", false);
user_pref("dom.battery.enabled", false);
user_pref("dom.enable_performance", false);
user_pref("dom.enable_resource_timing", false);
user_pref("dom.enable_user_timing", false);
user_pref("dom.event.highrestimestamp.enabled", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.netinfo.enabled", false);
user_pref("dom.telephony.enabled", false);
user_pref("dom.vibrator.enabled", false);
user_pref("dom.vr.enabled", false);
user_pref("dom.workers.sharedWorkers.enabled", false);
user_pref("gfx.downloadable_fonts.fallback_delay", -1);
user_pref("media.video_stats.enabled", false);
user_pref("plugin.expose_full_path", false);

EOF
fi

if [ "$PRIVATE_BROWSING_AUTOSTART" = 1 ]; then
    cat << EOF
// Private browsing
user_pref("browser.privatebrowsing.autostart", true);

EOF
fi

if [ "$TBB_USERAGENT" = 1 ]; then
    cat << EOF
// Match user agent used by Tor Browser
user_pref("browser.startup.homepage_override.buildID", "20100101");
user_pref("general.appname.override", "Netscape");
user_pref("general.appversion.override", "5.0 (Windows)");
user_pref("general.buildID.override", "20100101");
user_pref("general.oscpu.override", "Windows NT 6.1");
user_pref("general.platform.override", "Win32");
user_pref("general.productSub.override", "20100101");
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0");

EOF
fi

if [ "$TRACKING_PROTECTION" = 1 ]; then
    cat << EOF
// Tracking protection
user_pref("privacy.trackingprotection.enabled", true);

EOF
fi

